import { ModulePreset, PinakeModuleDescriptor } from '../types';

export const moduleDescriptors: PinakeModuleDescriptor[] = [
	{
		id: 'API',
		title: 'API',
		version: '0.1.0',
		description: 'REST API documentation scaffold.',
		dependencies: [],
		rootFolder: '03_Development/API',
		files: [
			{ relativePath: '03_Development/API/Overview.md', content: '# API Overview\n\nDescribe the API purpose, consumers, protocols, and lifecycle.\n' },
			{ relativePath: '03_Development/API/Authentication.md', content: '# API Authentication\n\nDocument authentication schemes, token formats, scopes, and examples.\n' },
			{ relativePath: '03_Development/API/Endpoints.md', content: '# API Endpoints\n\n| Method | Path | Description |\n| --- | --- | --- |\n| GET | /health | Health check endpoint. |\n' },
			{ relativePath: '03_Development/API/Errors.md', content: '# API Errors\n\nDocument common HTTP status codes, error bodies, and retry behavior.\n' },
			{ relativePath: '03_Development/API/Versioning.md', content: '# API Versioning\n\nDocument URL, header, or media type versioning conventions.\n' },
			{ relativePath: '03_Development/API/RateLimiting.md', content: '# Rate Limiting\n\nDocument quotas, throttling responses, and client retry guidance.\n' },
			{ relativePath: '03_Development/API/SDKs.md', content: '# SDKs\n\nList official and community client libraries.\n' },
			{ relativePath: '03_Development/API/Examples.md', content: '# API Examples\n\nAdd request and response examples for key workflows.\n' },
			{ relativePath: '03_Development/API/openapi.yaml', content: 'openapi: 3.1.0\ninfo:\n  title: Project API\n  version: 0.1.0\npaths: {}\n' },
		],
	},
	{
		id: 'Database',
		title: 'Database',
		version: '0.1.0',
		description: 'Database schema, migrations, and operational documentation.',
		dependencies: [],
		rootFolder: '03_Development/Database',
		files: [
			{ relativePath: '03_Development/Database/Overview.md', content: '# Database Overview\n\nDescribe the database engine, purpose, ownership, and environments.\n' },
			{ relativePath: '03_Development/Database/Schema.md', content: '# Database Schema\n\nDescribe tables, collections, diagrams, and schema boundaries.\n' },
			{ relativePath: '03_Development/Database/Entities.md', content: '# Entities\n\nDocument important entities, fields, and invariants.\n' },
			{ relativePath: '03_Development/Database/Relationships.md', content: '# Relationships\n\nDocument foreign keys, references, and cardinality.\n' },
			{ relativePath: '03_Development/Database/Indexes.md', content: '# Indexes\n\nDocument indexes, constraints, and performance intent.\n' },
			{ relativePath: '03_Development/Database/Migrations.md', content: '# Migrations\n\nDocument migration tools, commands, rollback policy, and review expectations.\n' },
			{ relativePath: '03_Development/Database/Performance.md', content: '# Database Performance\n\nDocument query analysis, tuning, and benchmarks.\n' },
			{ relativePath: '03_Development/Database/Backup.md', content: '# Database Backup\n\nDocument backup and restore procedures.\n' },
		],
	},
	{
		id: 'Docker',
		title: 'Docker',
		version: '0.1.0',
		description: 'Containerization documentation.',
		dependencies: [],
		rootFolder: '05_Operations/Docker',
		files: [
			{ relativePath: '05_Operations/Docker/Overview.md', content: '# Docker\n\nDocument containerization goals, base images, and supported workflows.\n' },
			{ relativePath: '05_Operations/Docker/Images.md', content: '# Docker Images\n\nDocument image names, base images, build arguments, and publishing.\n' },
			{ relativePath: '05_Operations/Docker/Containers.md', content: '# Containers\n\nDocument container runtime configuration and lifecycle.\n' },
			{ relativePath: '05_Operations/Docker/Volumes.md', content: '# Volumes\n\nDocument persistent and temporary volume usage.\n' },
			{ relativePath: '05_Operations/Docker/Networks.md', content: '# Networks\n\nDocument container networking and service discovery.\n' },
			{ relativePath: '05_Operations/Docker/Compose.md', content: '# Docker Compose\n\nDocument local compose services, profiles, and commands.\n' },
		],
	},
	{
		id: 'Kubernetes',
		title: 'Kubernetes',
		version: '0.1.0',
		description: 'Kubernetes deployment documentation.',
		dependencies: ['Docker'],
		rootFolder: '05_Operations/Kubernetes',
		files: [
			{ relativePath: '05_Operations/Kubernetes/Overview.md', content: '# Kubernetes\n\nDocument clusters, namespaces, deployment environments, and ownership.\n' },
			{ relativePath: '05_Operations/Kubernetes/Architecture.md', content: '# Kubernetes Architecture\n\nDocument Pods, Services, Ingress, Deployments, and supporting resources.\n' },
			{ relativePath: '05_Operations/Kubernetes/Manifests.md', content: '# Manifests\n\nDocument manifest structure, overlays, and review flow.\n' },
			{ relativePath: '05_Operations/Kubernetes/Services.md', content: '# Services\n\nDocument service exposure, ports, and discovery.\n' },
			{ relativePath: '05_Operations/Kubernetes/Ingress.md', content: '# Ingress\n\nDocument routes, TLS, hosts, and ingress controller details.\n' },
			{ relativePath: '05_Operations/Kubernetes/Deployments.md', content: '# Deployments\n\nDocument replicas, rollout strategy, and health checks.\n' },
			{ relativePath: '05_Operations/Kubernetes/ConfigMaps.md', content: '# ConfigMaps\n\nDocument non-secret runtime configuration.\n' },
			{ relativePath: '05_Operations/Kubernetes/Secrets.md', content: '# Secrets\n\nDocument secret references and rotation policy without storing secret values.\n' },
		],
	},
	{
		id: 'CI/CD',
		title: 'CI/CD',
		version: '0.1.0',
		description: 'Continuous integration and delivery documentation.',
		dependencies: [],
		rootFolder: '05_Operations/CI-CD',
		files: [
			{ relativePath: '05_Operations/CI-CD/Overview.md', content: '# CI/CD\n\nDocument platforms, workflow ownership, and release gates.\n' },
			{ relativePath: '05_Operations/CI-CD/Pipelines.md', content: '# Pipelines\n\nDocument build, test, packaging, and deployment pipelines.\n' },
			{ relativePath: '05_Operations/CI-CD/Workflows.md', content: '# Workflows\n\nDocument workflow files, triggers, jobs, and required checks.\n' },
			{ relativePath: '05_Operations/CI-CD/Environments.md', content: '# Environments\n\nDocument staging, production, approvals, and rollback paths.\n' },
		],
	},
	{
		id: 'Frontend',
		title: 'Frontend',
		version: '0.1.0',
		description: 'Web frontend documentation.',
		dependencies: [],
		rootFolder: '03_Development/Frontend',
		files: [
			{ relativePath: '03_Development/Frontend/Overview.md', content: '# Frontend\n\nDocument framework, build tool, design system, and browser support.\n' },
			{ relativePath: '03_Development/Frontend/Components.md', content: '# Components\n\nDocument key components, ownership, props, and design constraints.\n' },
			{ relativePath: '03_Development/Frontend/Routing.md', content: '# Routing\n\nDocument routes, guards, layouts, and navigation behavior.\n' },
			{ relativePath: '03_Development/Frontend/State.md', content: '# State Management\n\nDocument local, server, and global state decisions.\n' },
			{ relativePath: '03_Development/Frontend/Styling.md', content: '# Styling\n\nDocument CSS architecture, tokens, themes, and responsive rules.\n' },
			{ relativePath: '03_Development/Frontend/Accessibility.md', content: '# Accessibility\n\nDocument accessibility requirements, testing, and known limitations.\n' },
		],
	},
	{
		id: 'Mobile',
		title: 'Mobile',
		version: '0.1.0',
		description: 'Mobile app documentation.',
		dependencies: [],
		rootFolder: '03_Development/Mobile',
		files: [
			{ relativePath: '03_Development/Mobile/Overview.md', content: '# Mobile\n\nDocument supported platforms, framework, and release channels.\n' },
			{ relativePath: '03_Development/Mobile/Screens.md', content: '# Screens\n\nDocument screens, flows, navigation, and platform differences.\n' },
			{ relativePath: '03_Development/Mobile/Plugins.md', content: '# Plugins\n\nDocument native plugins, permissions, and integration notes.\n' },
			{ relativePath: '03_Development/Mobile/State.md', content: '# Mobile State\n\nDocument state management and offline behavior.\n' },
			{ relativePath: '03_Development/Mobile/StoreRelease.md', content: '# Store Release\n\nDocument build, signing, review, and release procedures.\n' },
		],
	},
	{
		id: 'Authentication',
		title: 'Authentication',
		version: '0.1.0',
		description: 'Authentication and identity documentation.',
		dependencies: [],
		rootFolder: '03_Development/Authentication',
		files: [
			{ relativePath: '03_Development/Authentication/Overview.md', content: '# Authentication\n\nDocument authentication strategy, identity providers, and token lifecycle.\n' },
			{ relativePath: '03_Development/Authentication/Users.md', content: '# Users\n\nDocument user model, registration, password handling, and account lifecycle.\n' },
			{ relativePath: '03_Development/Authentication/Permissions.md', content: '# Permissions\n\nDocument roles, scopes, ACLs, and authorization checks.\n' },
			{ relativePath: '03_Development/Authentication/Session.md', content: '# Sessions\n\nDocument cookies, refresh tokens, expiration, and revocation.\n' },
			{ relativePath: '03_Development/Authentication/OAuth.md', content: '# OAuth\n\nDocument OAuth providers, flows, callback URLs, and scopes.\n' },
		],
	},
];

export const modulePresets: ModulePreset[] = [
	{
		id: 'backend-node',
		title: 'Backend (Node.js)',
		description: 'API, Database, Authentication, Docker, and CI/CD.',
		moduleIds: ['API', 'Database', 'Authentication', 'Docker', 'CI/CD'],
	},
	{
		id: 'frontend-react',
		title: 'Frontend (React)',
		description: 'Frontend, API, Docker, and CI/CD.',
		moduleIds: ['Frontend', 'API', 'Docker', 'CI/CD'],
	},
	{
		id: 'fullstack',
		title: 'Fullstack',
		description: 'Frontend, API, Database, Authentication, Docker, and CI/CD.',
		moduleIds: ['Frontend', 'API', 'Database', 'Authentication', 'Docker', 'CI/CD'],
	},
	{
		id: 'operations',
		title: 'Operations',
		description: 'Docker, Kubernetes, and CI/CD.',
		moduleIds: ['Docker', 'Kubernetes', 'CI/CD'],
	},
];

export function getModuleDescriptor(id: string): PinakeModuleDescriptor | undefined {
	return moduleDescriptors.find((descriptor) => descriptor.id === id);
}
