import { ModulePreset, PinakeModuleDescriptor } from '../types';

export const moduleDescriptors: PinakeModuleDescriptor[] = [
	{
		id: 'API',
		title: 'API',
		version: '0.1.0',
		description: 'REST API documentation scaffold.',
		dependencies: [],
		rootFolder: '03_Development/API',
		files: [
			{ relativePath: '03_Development/API/Overview.md', content: '# API Overview\n\nDescribe the API purpose, consumers, protocols, and lifecycle.\n' },
			{ relativePath: '03_Development/API/Authentication.md', content: '# API Authentication\n\nDocument authentication schemes, token formats, scopes, and examples.\n' },
			{ relativePath: '03_Development/API/Endpoints.md', content: '# API Endpoints\n\n| Method | Path | Description |\n| --- | --- | --- |\n| GET | /health | Health check endpoint. |\n' },
			{ relativePath: '03_Development/API/Errors.md', content: '# API Errors\n\nDocument common HTTP status codes, error bodies, and retry behavior.\n' },
			{ relativePath: '03_Development/API/Versioning.md', content: '# API Versioning\n\nDocument URL, header, or media type versioning conventions.\n' },
			{ relativePath: '03_Development/API/RateLimiting.md', content: '# Rate Limiting\n\nDocument quotas, throttling responses, and client retry guidance.\n' },
			{ relativePath: '03_Development/API/SDKs.md', content: '# SDKs\n\nList official and community client libraries.\n' },
			{ relativePath: '03_Development/API/Examples.md', content: '# API Examples\n\nAdd request and response examples for key workflows.\n' },
			{ relativePath: '03_Development/API/openapi.yaml', content: 'openapi: 3.1.0\ninfo:\n  title: Project API\n  version: 0.1.0\npaths: {}\n' },
		],
	},
	{
		id: 'Database',
		title: 'Database',
		version: '0.1.0',
		description: 'Database schema, migrations, and operational documentation.',
		dependencies: [],
		rootFolder: '03_Development/Database',
		files: [
			{ relativePath: '03_Development/Database/Overview.md', content: '# Database Overview\n\nDescribe the database engine, purpose, ownership, and environments.\n' },
			{ relativePath: '03_Development/Database/Schema.md', content: '# Database Schema\n\nDescribe tables, collections, diagrams, and schema boundaries.\n' },
			{ relativePath: '03_Development/Database/Entities.md', content: '# Entities\n\nDocument important entities, fields, and invariants.\n' },
			{ relativePath: '03_Development/Database/Relationships.md', content: '# Relationships\n\nDocument foreign keys, references, and cardinality.\n' },
			{ relativePath: '03_Development/Database/Indexes.md', content: '# Indexes\n\nDocument indexes, constraints, and performance intent.\n' },
			{ relativePath: '03_Development/Database/Migrations.md', content: '# Migrations\n\nDocument migration tools, commands, rollback policy, and review expectations.\n' },
			{ relativePath: '03_Development/Database/Performance.md', content: '# Database Performance\n\nDocument query analysis, tuning, and benchmarks.\n' },
			{ relativePath: '03_Development/Database/Backup.md', content: '# Database Backup\n\nDocument backup and restore procedures.\n' },
		],
	},
	{
		id: 'Docker',
		title: 'Docker',
		version: '0.1.0',
		description: 'Containerization documentation.',
		dependencies: [],
		rootFolder: '05_Operations/Docker',
		files: [
			{ relativePath: '05_Operations/Docker/Overview.md', content: '# Docker\n\nDocument containerization goals, base images, and supported workflows.\n' },
			{ relativePath: '05_Operations/Docker/Images.md', content: '# Docker Images\n\nDocument image names, base images, build arguments, and publishing.\n' },
			{ relativePath: '05_Operations/Docker/Containers.md', content: '# Containers\n\nDocument container runtime configuration and lifecycle.\n' },
			{ relativePath: '05_Operations/Docker/Volumes.md', content: '# Volumes\n\nDocument persistent and temporary volume usage.\n' },
			{ relativePath: '05_Operations/Docker/Networks.md', content: '# Networks\n\nDocument container networking and service discovery.\n' },
			{ relativePath: '05_Operations/Docker/Compose.md', content: '# Docker Compose\n\nDocument local compose services, profiles, and commands.\n' },
		],
	},
	{
		id: 'Kubernetes',
		title: 'Kubernetes',
		version: '0.1.0',
		description: 'Kubernetes deployment documentation.',
		dependencies: ['Docker'],
		rootFolder: '05_Operations/Kubernetes',
		files: [
			{ relativePath: '05_Operations/Kubernetes/Overview.md', content: '# Kubernetes\n\nDocument clusters, namespaces, deployment environments, and ownership.\n' },
			{ relativePath: '05_Operations/Kubernetes/Architecture.md', content: '# Kubernetes Architecture\n\nDocument Pods, Services, Ingress, Deployments, and supporting resources.\n' },
			{ relativePath: '05_Operations/Kubernetes/Manifests.md', content: '# Manifests\n\nDocument manifest structure, overlays, and review flow.\n' },
			{ relativePath: '05_Operations/Kubernetes/Services.md', content: '# Services\n\nDocument service exposure, ports, and discovery.\n' },
			{ relativePath: '05_Operations/Kubernetes/Ingress.md', content: '# Ingress\n\nDocument routes, TLS, hosts, and ingress controller details.\n' },
			{ relativePath: '05_Operations/Kubernetes/Deployments.md', content: '# Deployments\n\nDocument replicas, rollout strategy, and health checks.\n' },
			{ relativePath: '05_Operations/Kubernetes/ConfigMaps.md', content: '# ConfigMaps\n\nDocument non-secret runtime configuration.\n' },
			{ relativePath: '05_Operations/Kubernetes/Secrets.md', content: '# Secrets\n\nDocument secret references and rotation policy without storing secret values.\n' },
		],
	},
	{
		id: 'CI/CD',
		title: 'CI/CD',
		version: '0.1.0',
		description: 'Continuous integration and delivery documentation.',
		dependencies: [],
		rootFolder: '05_Operations/CI-CD',
		files: [
			{ relativePath: '05_Operations/CI-CD/Overview.md', content: '# CI/CD\n\nDocument platforms, workflow ownership, and release gates.\n' },
			{ relativePath: '05_Operations/CI-CD/Pipelines.md', content: '# Pipelines\n\nDocument build, test, packaging, and deployment pipelines.\n' },
			{ relativePath: '05_Operations/CI-CD/Workflows.md', content: '# Workflows\n\nDocument workflow files, triggers, jobs, and required checks.\n' },
			{ relativePath: '05_Operations/CI-CD/Environments.md', content: '# Environments\n\nDocument staging, production, approvals, and rollback paths.\n' },
		],
	},
	{
		id: 'Frontend',
		title: 'Frontend',
		version: '0.1.0',
		description: 'Web frontend documentation.',
		dependencies: [],
		rootFolder: '03_Development/Frontend',
		files: [
			{ relativePath: '03_Development/Frontend/Overview.md', content: '# Frontend\n\nDocument framework, build tool, design system, and browser support.\n' },
			{ relativePath: '03_Development/Frontend/Components.md', content: '# Components\n\nDocument key components, ownership, props, and design constraints.\n' },
			{ relativePath: '03_Development/Frontend/Routing.md', content: '# Routing\n\nDocument routes, guards, layouts, and navigation behavior.\n' },
			{ relativePath: '03_Development/Frontend/State.md', content: '# State Management\n\nDocument local, server, and global state decisions.\n' },
			{ relativePath: '03_Development/Frontend/Styling.md', content: '# Styling\n\nDocument CSS architecture, tokens, themes, and responsive rules.\n' },
			{ relativePath: '03_Development/Frontend/Accessibility.md', content: '# Accessibility\n\nDocument accessibility requirements, testing, and known limitations.\n' },
		],
	},
	{
		id: 'Mobile',
		title: 'Mobile',
		version: '0.1.0',
		description: 'Mobile app documentation.',
		dependencies: [],
		rootFolder: '03_Development/Mobile',
		files: [
			{ relativePath: '03_Development/Mobile/Overview.md', content: '# Mobile\n\nDocument supported platforms, framework, and release channels.\n' },
			{ relativePath: '03_Development/Mobile/Screens.md', content: '# Screens\n\nDocument screens, flows, navigation, and platform differences.\n' },
			{ relativePath: '03_Development/Mobile/Plugins.md', content: '# Plugins\n\nDocument native plugins, permissions, and integration notes.\n' },
			{ relativePath: '03_Development/Mobile/State.md', content: '# Mobile State\n\nDocument state management and offline behavior.\n' },
			{ relativePath: '03_Development/Mobile/StoreRelease.md', content: '# Store Release\n\nDocument build, signing, review, and release procedures.\n' },
		],
	},
	{
		id: 'Authentication',
		title: 'Authentication',
		version: '0.1.0',
		description: 'Authentication and identity documentation.',
		dependencies: [],
		rootFolder: '03_Development/Authentication',
		files: [
			{ relativePath: '03_Development/Authentication/Overview.md', content: '# Authentication\n\nDocument authentication strategy, identity providers, and token lifecycle.\n' },
			{ relativePath: '03_Development/Authentication/Users.md', content: '# Users\n\nDocument user model, registration, password handling, and account lifecycle.\n' },
			{ relativePath: '03_Development/Authentication/Permissions.md', content: '# Permissions\n\nDocument roles, scopes, ACLs, and authorization checks.\n' },
			{ relativePath: '03_Development/Authentication/Session.md', content: '# Sessions\n\nDocument cookies, refresh tokens, expiration, and revocation.\n' },
			{ relativePath: '03_Development/Authentication/OAuth.md', content: '# OAuth\n\nDocument OAuth providers, flows, callback URLs, and scopes.\n' },
		],
	},
	{
		id: 'GraphQL',
		title: 'GraphQL',
		version: '0.1.0',
		description: 'GraphQL schema, resolver, operation, and client documentation.',
		dependencies: ['API'],
		rootFolder: '03_Development/GraphQL',
		files: [
			{ relativePath: '03_Development/GraphQL/Overview.md', content: '# GraphQL Overview\n\nDocument the GraphQL API purpose, consumers, schema ownership, and lifecycle.\n' },
			{ relativePath: '03_Development/GraphQL/Schema.md', content: '# GraphQL Schema\n\nDocument root types, important object types, custom scalars, directives, and schema conventions.\n' },
			{ relativePath: '03_Development/GraphQL/Resolvers.md', content: '# Resolvers\n\nDocument resolver responsibilities, data loading, authorization, and error behavior.\n' },
			{ relativePath: '03_Development/GraphQL/Operations.md', content: '# Operations\n\nList important queries, mutations, subscriptions, variables, and example responses.\n' },
			{ relativePath: '03_Development/GraphQL/Clients.md', content: '# GraphQL Clients\n\nDocument client generation, fragments, caching, persisted operations, and compatibility expectations.\n' },
			{ relativePath: '03_Development/GraphQL/Errors.md', content: '# GraphQL Errors\n\nDocument error formats, partial responses, retry guidance, and user-facing error mapping.\n' },
		],
	},
	{
		id: 'gRPC',
		title: 'gRPC',
		version: '0.1.0',
		description: 'gRPC service, protobuf contract, streaming, and compatibility documentation.',
		dependencies: ['API'],
		rootFolder: '03_Development/gRPC',
		files: [
			{ relativePath: '03_Development/gRPC/Overview.md', content: '# gRPC Overview\n\nDocument service ownership, consumers, transport assumptions, and runtime environments.\n' },
			{ relativePath: '03_Development/gRPC/ProtoContracts.md', content: '# Protobuf Contracts\n\nDocument proto packages, message schemas, field ownership, and generated code locations.\n' },
			{ relativePath: '03_Development/gRPC/Services.md', content: '# gRPC Services\n\nList services, RPC methods, request/response types, deadlines, and authorization expectations.\n' },
			{ relativePath: '03_Development/gRPC/Streaming.md', content: '# Streaming\n\nDocument unary, server streaming, client streaming, and bidirectional streaming behavior.\n' },
			{ relativePath: '03_Development/gRPC/Errors.md', content: '# gRPC Errors\n\nDocument status codes, retryable failures, metadata, and client handling guidance.\n' },
			{ relativePath: '03_Development/gRPC/Compatibility.md', content: '# gRPC Compatibility\n\nDocument backward compatibility rules, reserved fields, versioning, and deprecation policy.\n' },
		],
	},
	{
		id: 'WebSocket',
		title: 'WebSocket',
		version: '0.1.0',
		description: 'Realtime WebSocket protocol, event, channel, and reliability documentation.',
		dependencies: ['API'],
		rootFolder: '03_Development/WebSocket',
		files: [
			{ relativePath: '03_Development/WebSocket/Overview.md', content: '# WebSocket Overview\n\nDocument realtime use cases, connection lifecycle, supported clients, and service ownership.\n' },
			{ relativePath: '03_Development/WebSocket/Protocol.md', content: '# WebSocket Protocol\n\nDocument message envelopes, versioning, heartbeats, acknowledgements, and close codes.\n' },
			{ relativePath: '03_Development/WebSocket/Events.md', content: '# WebSocket Events\n\nList inbound and outbound events, payload schemas, ordering, and delivery expectations.\n' },
			{ relativePath: '03_Development/WebSocket/Channels.md', content: '# Channels\n\nDocument topics, rooms, subscriptions, authorization, fanout, and tenant boundaries.\n' },
			{ relativePath: '03_Development/WebSocket/Reliability.md', content: '# WebSocket Reliability\n\nDocument reconnect behavior, replay windows, backpressure, and failure handling.\n' },
		],
	},
	{
		id: 'Backend',
		title: 'Backend',
		version: '0.1.0',
		description: 'Backend service architecture, domain, jobs, configuration, and dependency documentation.',
		dependencies: [],
		rootFolder: '03_Development/Backend',
		files: [
			{ relativePath: '03_Development/Backend/Overview.md', content: '# Backend Overview\n\nDocument backend responsibilities, runtime shape, ownership, and important entry points.\n' },
			{ relativePath: '03_Development/Backend/Architecture.md', content: '# Backend Architecture\n\nDocument layers, boundaries, modules, dependency direction, and integration points.\n' },
			{ relativePath: '03_Development/Backend/DomainModel.md', content: '# Domain Model\n\nDocument core entities, invariants, workflows, and business rules.\n' },
			{ relativePath: '03_Development/Backend/Jobs.md', content: '# Jobs and Workers\n\nDocument background jobs, schedules, queues, retries, and operational expectations.\n' },
			{ relativePath: '03_Development/Backend/Configuration.md', content: '# Backend Configuration\n\nDocument environment variables, feature flags, config files, defaults, and secret references.\n' },
			{ relativePath: '03_Development/Backend/Dependencies.md', content: '# Backend Dependencies\n\nDocument internal packages, external services, libraries, and upgrade considerations.\n' },
		],
	},
	{
		id: 'Cache',
		title: 'Cache',
		version: '0.1.0',
		description: 'Caching strategy, key design, invalidation, performance, and operations documentation.',
		dependencies: [],
		rootFolder: '03_Development/Cache',
		files: [
			{ relativePath: '03_Development/Cache/Overview.md', content: '# Cache Overview\n\nDocument cache stores, ownership, use cases, and consistency expectations.\n' },
			{ relativePath: '03_Development/Cache/Keys.md', content: '# Cache Keys\n\nDocument key naming, namespaces, tenant boundaries, TTLs, and value formats.\n' },
			{ relativePath: '03_Development/Cache/Invalidation.md', content: '# Cache Invalidation\n\nDocument invalidation triggers, write-through behavior, stale data tolerance, and manual purge paths.\n' },
			{ relativePath: '03_Development/Cache/Performance.md', content: '# Cache Performance\n\nDocument hit-rate targets, memory limits, latency expectations, and measurement approach.\n' },
			{ relativePath: '03_Development/Cache/Operations.md', content: '# Cache Operations\n\nDocument dashboards, alerts, failover behavior, and recovery steps.\n' },
		],
	},
	{
		id: 'MessageQueue',
		title: 'Message Queue',
		version: '0.1.0',
		description: 'Queue, topic, producer, consumer, delivery, and failure handling documentation.',
		dependencies: [],
		rootFolder: '03_Development/MessageQueue',
		files: [
			{ relativePath: '03_Development/MessageQueue/Overview.md', content: '# Message Queue Overview\n\nDocument broker technology, use cases, ownership, and runtime topology.\n' },
			{ relativePath: '03_Development/MessageQueue/TopicsAndQueues.md', content: '# Topics and Queues\n\nList topics, queues, routing keys, partitions, retention, and consumers.\n' },
			{ relativePath: '03_Development/MessageQueue/ProducersConsumers.md', content: '# Producers and Consumers\n\nDocument producers, consumer groups, payload ownership, and processing responsibilities.\n' },
			{ relativePath: '03_Development/MessageQueue/DeliverySemantics.md', content: '# Delivery Semantics\n\nDocument ordering, idempotency, retries, deduplication, and exactly-once assumptions.\n' },
			{ relativePath: '03_Development/MessageQueue/FailureHandling.md', content: '# Failure Handling\n\nDocument dead-letter queues, poison messages, backoff, replay, and operator runbooks.\n' },
		],
	},
	{
		id: 'OAuth',
		title: 'OAuth',
		version: '0.1.0',
		description: 'OAuth clients, flows, scopes, token lifecycle, and provider documentation.',
		dependencies: ['Authentication'],
		rootFolder: '03_Development/OAuth',
		files: [
			{ relativePath: '03_Development/OAuth/Overview.md', content: '# OAuth Overview\n\nDocument identity providers, clients, grants, environments, and ownership.\n' },
			{ relativePath: '03_Development/OAuth/Flows.md', content: '# OAuth Flows\n\nDocument authorization code, PKCE, client credentials, refresh, device, or custom flows used by the project.\n' },
			{ relativePath: '03_Development/OAuth/Clients.md', content: '# OAuth Clients\n\nDocument client registrations, redirect URIs, allowed origins, and environment differences.\n' },
			{ relativePath: '03_Development/OAuth/Scopes.md', content: '# OAuth Scopes\n\nDocument scopes, claims, consent, least-privilege rules, and authorization checks.\n' },
			{ relativePath: '03_Development/OAuth/TokenLifecycle.md', content: '# Token Lifecycle\n\nDocument token formats, expiration, refresh, revocation, rotation, and storage guidance.\n' },
		],
	},
	{
		id: 'IaC',
		title: 'Infrastructure as Code',
		version: '0.1.0',
		description: 'Infrastructure-as-code providers, modules, state, environments, and change workflow documentation.',
		dependencies: [],
		rootFolder: '05_Operations/IaC',
		files: [
			{ relativePath: '05_Operations/IaC/Overview.md', content: '# Infrastructure as Code\n\nDocument IaC tools, ownership, repositories, environments, and provisioning scope.\n' },
			{ relativePath: '05_Operations/IaC/Providers.md', content: '# Providers\n\nDocument cloud providers, accounts, subscriptions, regions, and required permissions.\n' },
			{ relativePath: '05_Operations/IaC/Modules.md', content: '# IaC Modules\n\nDocument reusable modules, inputs, outputs, versioning, and ownership.\n' },
			{ relativePath: '05_Operations/IaC/State.md', content: '# IaC State\n\nDocument state backends, locking, recovery, drift handling, and access rules.\n' },
			{ relativePath: '05_Operations/IaC/Environments.md', content: '# IaC Environments\n\nDocument workspace layout, variables, promotion flow, and environment-specific differences.\n' },
			{ relativePath: '05_Operations/IaC/ChangeManagement.md', content: '# IaC Change Management\n\nDocument plan review, approvals, apply process, rollbacks, and emergency changes.\n' },
		],
	},
	{
		id: 'Monitoring',
		title: 'Monitoring',
		version: '0.1.0',
		description: 'Metrics, dashboards, alerts, SLOs, and incident review documentation.',
		dependencies: [],
		rootFolder: '05_Operations/Monitoring',
		files: [
			{ relativePath: '05_Operations/Monitoring/Overview.md', content: '# Monitoring Overview\n\nDocument monitoring tools, ownership, coverage, and operating expectations.\n' },
			{ relativePath: '05_Operations/Monitoring/Metrics.md', content: '# Metrics\n\nDocument core product, service, infrastructure, and business metrics.\n' },
			{ relativePath: '05_Operations/Monitoring/Dashboards.md', content: '# Dashboards\n\nDocument dashboards, links, intended audience, and interpretation notes.\n' },
			{ relativePath: '05_Operations/Monitoring/Alerts.md', content: '# Alerts\n\nDocument alert rules, severity, routing, noise policy, and response expectations.\n' },
			{ relativePath: '05_Operations/Monitoring/SLOs.md', content: '# SLOs\n\nDocument service-level objectives, error budgets, measurement windows, and review cadence.\n' },
			{ relativePath: '05_Operations/Monitoring/IncidentReview.md', content: '# Incident Review\n\nDocument incident review process, timelines, action items, and learning loops.\n' },
		],
	},
	{
		id: 'Security',
		title: 'Security',
		version: '0.1.0',
		description: 'Threat model, secrets, access control, data handling, and security review documentation.',
		dependencies: [],
		rootFolder: '04_Architecture/Security',
		files: [
			{ relativePath: '04_Architecture/Security/Overview.md', content: '# Security Overview\n\nDocument security ownership, boundaries, assumptions, and critical assets.\n' },
			{ relativePath: '04_Architecture/Security/ThreatModel.md', content: '# Threat Model\n\nDocument actors, trust boundaries, attack paths, mitigations, and residual risks.\n' },
			{ relativePath: '04_Architecture/Security/DataClassification.md', content: '# Data Classification\n\nDocument sensitive data categories, retention, access rules, and handling requirements.\n' },
			{ relativePath: '04_Architecture/Security/Secrets.md', content: '# Secrets\n\nDocument secret sources, rotation, storage, local development handling, and incident response.\n' },
			{ relativePath: '04_Architecture/Security/AccessControl.md', content: '# Access Control\n\nDocument roles, permissions, policy enforcement points, and audit requirements.\n' },
			{ relativePath: '04_Architecture/Security/ReviewChecklist.md', content: '# Security Review Checklist\n\nList review questions for authentication, authorization, data handling, dependencies, and operations.\n' },
		],
	},
	{
		id: 'CLI',
		title: 'CLI',
		version: '0.1.0',
		description: 'Command-line interface commands, configuration, distribution, and troubleshooting documentation.',
		dependencies: [],
		rootFolder: '03_Development/CLI',
		files: [
			{ relativePath: '03_Development/CLI/Overview.md', content: '# CLI Overview\n\nDocument the CLI purpose, audiences, installation paths, and supported platforms.\n' },
			{ relativePath: '03_Development/CLI/Commands.md', content: '# CLI Commands\n\nList commands, arguments, flags, defaults, examples, and exit codes.\n' },
			{ relativePath: '03_Development/CLI/Configuration.md', content: '# CLI Configuration\n\nDocument config files, environment variables, precedence, and profiles.\n' },
			{ relativePath: '03_Development/CLI/Distribution.md', content: '# CLI Distribution\n\nDocument packaging, release channels, checksums, and upgrade guidance.\n' },
			{ relativePath: '03_Development/CLI/Troubleshooting.md', content: '# CLI Troubleshooting\n\nDocument common errors, diagnostics, logs, and support handoff details.\n' },
		],
	},
	{
		id: 'SDK',
		title: 'SDK',
		version: '0.1.0',
		description: 'SDK installation, API reference, examples, versioning, and release documentation.',
		dependencies: ['API'],
		rootFolder: '03_Development/SDK',
		files: [
			{ relativePath: '03_Development/SDK/Overview.md', content: '# SDK Overview\n\nDocument supported languages, package names, generated sources, and ownership.\n' },
			{ relativePath: '03_Development/SDK/Installation.md', content: '# SDK Installation\n\nDocument package managers, versions, authentication, and setup examples.\n' },
			{ relativePath: '03_Development/SDK/APIReference.md', content: '# SDK API Reference\n\nDocument clients, methods, models, errors, pagination, and retries.\n' },
			{ relativePath: '03_Development/SDK/Examples.md', content: '# SDK Examples\n\nAdd minimal examples for authentication, common workflows, and error handling.\n' },
			{ relativePath: '03_Development/SDK/Versioning.md', content: '# SDK Versioning\n\nDocument compatibility, release cadence, deprecations, and migration guidance.\n' },
		],
	},
	{
		id: 'Microservice',
		title: 'Microservice',
		version: '0.1.0',
		description: 'Microservice boundaries, communication, data ownership, deployment, and operations documentation.',
		dependencies: ['API', 'Docker', 'Monitoring'],
		rootFolder: '04_Architecture/Microservice',
		files: [
			{ relativePath: '04_Architecture/Microservice/Overview.md', content: '# Microservice Overview\n\nDocument service purpose, ownership, runtime, dependencies, and consumers.\n' },
			{ relativePath: '04_Architecture/Microservice/Boundaries.md', content: '# Service Boundaries\n\nDocument responsibilities, non-responsibilities, domain boundaries, and shared assumptions.\n' },
			{ relativePath: '04_Architecture/Microservice/Communication.md', content: '# Communication\n\nDocument synchronous APIs, async messaging, events, timeouts, retries, and fallback behavior.\n' },
			{ relativePath: '04_Architecture/Microservice/DataOwnership.md', content: '# Data Ownership\n\nDocument owned data, integration data, migrations, retention, and cross-service consistency.\n' },
			{ relativePath: '04_Architecture/Microservice/Deployment.md', content: '# Microservice Deployment\n\nDocument deployment units, environments, rollout strategy, health checks, and rollback paths.\n' },
			{ relativePath: '04_Architecture/Microservice/Operations.md', content: '# Microservice Operations\n\nDocument dashboards, alerts, runbooks, capacity notes, and support escalation.\n' },
		],
	},
];

export const modulePresets: ModulePreset[] = [
	{
		id: 'backend-node',
		title: 'Backend (Node.js)',
		description: 'API, Database, Authentication, Docker, and CI/CD.',
		moduleIds: ['API', 'Database', 'Authentication', 'Docker', 'CI/CD'],
	},
	{
		id: 'frontend-react',
		title: 'Frontend (React)',
		description: 'Frontend, API, Docker, and CI/CD.',
		moduleIds: ['Frontend', 'API', 'Docker', 'CI/CD'],
	},
	{
		id: 'fullstack',
		title: 'Fullstack',
		description: 'Frontend, API, Database, Authentication, Docker, and CI/CD.',
		moduleIds: ['Frontend', 'API', 'Database', 'Authentication', 'Docker', 'CI/CD'],
	},
	{
		id: 'operations',
		title: 'Operations',
		description: 'Docker, Kubernetes, and CI/CD.',
		moduleIds: ['Docker', 'Kubernetes', 'CI/CD'],
	},
	{
		id: 'api-platform',
		title: 'API Platform',
		description: 'REST API, GraphQL, gRPC, WebSocket, and SDK.',
		moduleIds: ['API', 'GraphQL', 'gRPC', 'WebSocket', 'SDK'],
	},
	{
		id: 'platform-services',
		title: 'Platform Services',
		description: 'Backend, Database, Cache, Message Queue, Authentication, and OAuth.',
		moduleIds: ['Backend', 'Database', 'Cache', 'MessageQueue', 'Authentication', 'OAuth'],
	},
	{
		id: 'cloud-native',
		title: 'Cloud Native',
		description: 'Docker, Kubernetes, IaC, Monitoring, Security, and CI/CD.',
		moduleIds: ['Docker', 'Kubernetes', 'IaC', 'Monitoring', 'Security', 'CI/CD'],
	},
	{
		id: 'microservice',
		title: 'Microservice',
		description: 'Microservice, API, Database, Message Queue, Docker, and Monitoring.',
		moduleIds: ['Microservice', 'API', 'Database', 'MessageQueue', 'Docker', 'Monitoring'],
	},
];

export function getModuleDescriptor(id: string): PinakeModuleDescriptor | undefined {
	return moduleDescriptors.find((descriptor) => descriptor.id === id);
}
